name: Release Version

on:
  push:
    branches:
      - main
    paths:
      - filament_scale_enhanced/fse_version.py

jobs:
  tag:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.output_version.outputs.version }}
    steps:
      - uses: actions/checkout@v2
      - name: collect_tag_version
        run: |
          echo VERSION=$(cat filament_scale_enhanced/fse_version.py | awk '{ print $3 }' |  sed  's/"//g') >> $GITHUB_ENV
      - name: Push tag
        uses: mathieudutour/github-tag-action@v5.5
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          custom_tag: ${{ env.VERSION }}
          tag_prefix: v
      - name: Output Version
        id: output_version
        run: echo "::set-output name=version::${{ env.VERSION }}"

  release:
    runs-on: ubuntu-latest
    needs: tag
    steps:
      - uses: actions/checkout@v2
        with:
         ref: "v${{ needs.tag.outputs.version }}"
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install test dependencies
        run: |
          pip install OctoPrint Mock.GPIO
          pip install .[test]
      - name: Run pytest
        run: pytest -v
      - name: Build package
        run: python setup.py sdist --formats=zip
      - name: Rename build artifact
        run: find dist/. -name "*.zip" -type f -exec bash -c 'x="{}"; mv -v "$x" "dist/Filament_Scale_Enhanced.zip"' \;
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          draft: false
          automatic_release_tag: "v${{ needs.tag.outputs.version }}"
          files: |
            LICENSE.txt
            dist/Filament_Scale_Enhanced.zip