name: Release Version

on:
  push:
    branches:
      - main

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: collect_tag_version
        run: |
          echo VERSION=$(cat filament_scale_enhanced/fse_version.py | awk '{ print $3 }' |  sed  's/"//g') >> $GITHUB_ENV
      - name: Push tag
        uses: mathieudutour/github-tag-action@v5.5
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          custom_tag: ${{ env.VERSION }}
          tag_prefix: v
