name: Run Release Tests

on:
  pull_request:
    branches:
      - main

jobs:
  release-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Ensure Version Bump
        run: |
          git fetch --no-tags --prune --depth=1 origin +refs/heads/main:refs/remotes/origin/main
          [[ ! -z "$(git diff --name-only origin/main HEAD -- filament_scale_enhanced/fse_version.py)" ]]
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install test dependencies
        run: |
          pip install OctoPrint Mock.GPIO
          pip install .[test]
      - name: Run pytest
        run: pytest -v
